version: '3'

services:
  chatapp:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: chatapp
    depends_on:
      - chatdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://chatdb:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"


  chatdb:
    image: 'postgres:13.1-alpine'
    container_name: chatdb
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - "5432:5432"